# Configurazione personalizzata di Gitleaks per NewsRSS
title = "NewsRSS Gitleaks Configuration"

# Ignora i falsi positivi comuni
[allowlist]
description = "Modelli consentiti (falsi positivi)"
paths = [
    '''(.*?)(png|jpg|gif|doc|docx|pdf|bin|xls|xlsx|ppt|pptx)$''',
    '''node_modules''',
    '''venv''',
]

# Regole personalizzate per il rilascio di eventuali segreti
[[rules]]
id = "generic-api-key"
description = "Generic API Key"
regex = '''(?i)((api|app|aws|slack|github|google|stripe|twilio)(_|-)?){0,2}(key|token|secret|password)(_|-)?[a-z0-9_-]*\s*[:=>]\s*['\"][0-9a-zA-Z\-_=+/]{16,45}['\"]'''
secretGroup = 4
entropy = 3.5
keywords = [
    "api",
    "key",
    "token",
    "secret",
    "password"
]

[[rules]]
id = "aws-access-key"
description = "AWS Access Key ID"
regex = '''(A3T[A-Z0-9]|AKIA|ACCA|AGPA|AIDA|AROA|AIPA|ANPA|ANVA|ASIA)[A-Z0-9]{16}'''
keywords = [
    "AKIA",
    "ACCA",
    "aws",
]

[[rules]]
id = "aws-secret-key"
description = "AWS Secret Access Key"
regex = '''(?i)(aws)?(.{0,20})?['\"][0-9a-zA-Z\/+]{40}['\"]'''
keywords = [
    "aws",
    "secret",
]

[[rules]]
id = "rss-credentials"
description = "Rileva credenziali RSS"
regex = '''(?i)(rss|feed)(_|-)?[a-z0-9_-]*(key|token|secret|password|credential)(_|-)?[a-z0-9_-]*\s*[:=>]\s*['\"][0-9a-zA-Z\-_=+/]{8,45}['\"]'''
keywords = [
    "rss",
    "feed",
    "credential",
]
